### ISSUE TITLE
[OSX, 0.1.6] No such file or directory: '/usr/local/lib/python3.6/site-packages/pubgis/pubgis_gui.ui

### ISSUE THREAD

**Issue by dabroz** [andrewzwicky/PUBGIS#33]
After installing version 0.1.6:

```
$ python3.6 -m pubgis
objc[2478]: Class QCocoaPageLayoutDelegate is implemented in both /usr/local/lib/python3.6/site-packages/cv2/.dylibs/QtGui (0x10f5b42b0) and /usr/local/lib/python3.6/site-packages/PyQt5/Qt/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x111d97ef0). One of the two will be used. Which one is undefined.
objc[2478]: Class QCocoaPrintPanelDelegate is implemented in both /usr/local/lib/python3.6/site-packages/cv2/.dylibs/QtGui (0x10f5b4328) and /usr/local/lib/python3.6/site-packages/PyQt5/Qt/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x111d97f40). One of the two will be used. Which one is undefined.
objc[2478]: Class QCocoaApplicationDelegate is implemented in both /usr/local/lib/python3.6/site-packages/cv2/.dylibs/QtGui (0x10f5b4030) and /usr/local/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x1151d57a0). One of the two will be used. Which one is undefined.
objc[2478]: Class QNSApplication is implemented in both /usr/local/lib/python3.6/site-packages/cv2/.dylibs/QtGui (0x10f5b3fe0) and /usr/local/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x1151d57f0). One of the two will be used. Which one is undefined.
objc[2478]: Class QCocoaMenuLoader is implemented in both /usr/local/lib/python3.6/site-packages/cv2/.dylibs/QtGui (0x10f5b3f90) and /usr/local/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x1151d5890). One of the two will be used. Which one is undefined.
objc[2478]: Class QNSOpenSavePanelDelegate is implemented in both /usr/local/lib/python3.6/site-packages/cv2/.dylibs/QtGui (0x10f5b4170) and /usr/local/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x1151d59d0). One of the two will be used. Which one is undefined.
objc[2478]: Class QNSImageView is implemented in both /usr/local/lib/python3.6/site-packages/cv2/.dylibs/QtGui (0x10f5b4350) and /usr/local/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x1151d5a70). One of the two will be used. Which one is undefined.
objc[2478]: Class QNSStatusItem is implemented in both /usr/local/lib/python3.6/site-packages/cv2/.dylibs/QtGui (0x10f5b43a0) and /usr/local/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x1151d5ac0). One of the two will be used. Which one is undefined.
objc[2478]: Class QNSMenu is implemented in both /usr/local/lib/python3.6/site-packages/cv2/.dylibs/QtGui (0x10f5b43c8) and /usr/local/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib (0x1151d5b10). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/pubgis/__main__.py", line 14, in <module>
    WIN = PUBGISMainWindow()
  File "/usr/local/lib/python3.6/site-packages/pubgis/gui.py", line 66, in __init__
    uic.loadUi(os.path.join(os.path.dirname(__file__), "pubgis_gui.ui"), self)
  File "/usr/local/lib/python3.6/site-packages/PyQt5/uic/__init__.py", line 226, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/local/lib/python3.6/site-packages/PyQt5/uic/Loader/loader.py", line 72, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "/usr/local/lib/python3.6/site-packages/PyQt5/uic/uiparser.py", line 1003, in parse
    document = parse(filename)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/etree/ElementTree.py", line 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/pubgis/pubgis_gui.ui'

$ ls /usr/local/lib/python3.6/site-packages/pubgis/
__init__.py		__pycache__		gui.py			match.py		minimap_iterators
__main__.py		color.py		images			match_result.py
```

**Comment by andrewzwicky** [comment]
This should be resolved in 78a5d021, v0.1.7
